[versions]
# libraries
junit = "4.13.2"
# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.2.21"
kover = "0.9.4"
ktlint = "1.8.0"
qodana = "2025.2.2"
shadow = "8.1.1"
slf4j="2.0.17"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ktlintRuleEngine = {  group = "com.pinterest.ktlint", name = "ktlint-rule-engine", version.ref = "ktlint" }
ktlintCliRulesetCore = {  group = "com.pinterest.ktlint", name = "ktlint-cli-ruleset-core", version.ref = "ktlint" }
ktlintCliReporterCore = {  group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-core", version.ref = "ktlint" }
ktlintCliReporterBaselineCore = {  group = "com.pinterest.ktlint", name = "ktlint-cli-reporter-baseline", version.ref = "ktlint" }
ktlintRulesetStandard = {  group = "com.pinterest.ktlint", name = "ktlint-ruleset-standard", version.ref = "ktlint" }
slf4j-api = {  group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
